name: bilu2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cloud_firestore: ^5.5.1
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.3
  firebase_core: null
  firebase_database: ^11.3.0
  firebase_messaging: ^15.2.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^18.0.1
  flutter_login: ^5.0.0
  font_awesome_flutter: ^10.8.0
  google_adsense: ^0.1.1
  google_fonts: ^6.2.1
  google_mobile_ads: ^5.2.0
  google_sign_in: ^6.2.2
  http: null
  image_picker: null
  intl: ^0.19.0
  local_auth: null
  permission_handler: null
  provider: null
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.0.1
  youtube_player_flutter: ^9.0.4
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/BILU Logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/BILU Logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/BILU Logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/BILU Logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
